CREATE TABLE pollings (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
title VARCHAR(64) NOT NULL,
option1 VARCHAR(64) DEFAULT NULL,
option2 VARCHAR(64) DEFAULT NULL,
option3 VARCHAR(64) DEFAULT NULL,
option4 VARCHAR(64) DEFAULT NULL,
enabled BOOLEAN DEFAULT FALSE,
primary key (id)
);

CREATE TABLE polling_results (
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
rid INTEGER NOT NULL,
username VARCHAR(50) NOT NULL,
voted INTEGER NOT NULL,
primary key (id),
FOREIGN KEY (username) REFERENCES users(username),
FOREIGN KEY (rid) REFERENCES pollings(id)
);